---
abstract: 'A collection of record-handling tools related to biology'
author:
  - 'Thomas Sibley <trsibley@uw.edu>'
build_requires:
  App::RecordStream::Test::Tester: v4.0.0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-RecordStream-Bio
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  App::RecordStream::Operation: v4.0.0
  perl: 5.010
resources:
  bugtracker: https://github.com/MullinsLab/App-RecordStream-Bio/issues
  homepage: https://github.com/MullinsLab/App-RecordStream-Bio
  repository: https://github.com/MullinsLab/App-RecordStream-Bio.git
version: 0.09
